### ISSUE TITLE
Add character limit per message.

### ISSUE THREAD

**Issue by efenow** [Silverflag/sf-clearnet#7]
Add a character limit of about 500 or something, so that if line wrapping gets added, there wont be a text wall.

**Comment by YetAnotherNotHacking** [comment]
I am working on this now. I will make the limit 1024. It allows long legit messages but makes it hard to fill it with huge blocks of text.

there is still no limit on the length of the username. Input on the length limit for that would be helpful

maybe have a hidden limit of like 20 characters and if they exceed it, then give them a 4 character string of random letters or something

**Comment by YetAnotherNotHacking** [comment]
I have added logic to set the username to "toolong" if it is longer than 14 chars (tottaly is not because 15 is not working for some reason) (I just made a typo and I am lazy it would work if I changed it)

**Comment by YetAnotherNotHacking** [comment]
1024 is too long.

**Comment by YetAnotherNotHacking** [comment]
https://github.com/Silverflag/sf-clearnet/commit/3d700a6eff548066c3c3577b52fe7d62d1807a34
