### ISSUE TITLE
Improve line wrapping in Anon Chat

### ISSUE THREAD

**Issue by efenow** [Silverflag/sf-clearnet#8]
If someone types something long, it mostly doesn't line-wrap properly. Adding this will also work great with #7

**Comment by YetAnotherNotHacking** [comment]
I might also want to fix it to dynamically change how much of the chat it is loading, it downloads the entire chat and scrolls to the bottom about 2 times per second.

**Comment by YetAnotherNotHacking** [comment]
not sure this one is much of an issue, was sorta fixed from the mesage length limit if it was an issue in the past.
